name: CI
on:
  push:
    branches:
      - dev
  pull_request:
    branches: [dev, main]



jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    container:
      image: mcr.microsoft.com/playwright:v1.42.1-jammy
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - name: Restore cached npm dependencies
        id: cache-dependencies-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress # needed for the Cypress binary
          key: npm-dependencies-${{ hashFiles('package-lock.json') }}
      - run: npm install --frozen-lockfile
      - name: Cache npm dependencies
        id: cache-dependencies-save
        uses: actions/cache/save@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress # needed for the Cypress binary
          key: ${{ steps.cache-dependencies-restore.outputs.cache-primary-key }}
      - uses: nrwl/nx-set-shas@v4
      # This line is needed for nx affected to work when CI is running on a PR
      - run: git config --system --add safe.directory "$GITHUB_WORKSPACE"
      - run: git branch --track main origin/main
      - run: npx nx affected -t lint test build --parallel=3
      - run: HOME=/root npx nx affected -t e2e --parallel=1
